VOID SetHook_ZwOpenProcess( void );
VOID SetHook_ZwOpenThread( void );
VOID SetHook_ZwWriteVirtualMemory( void );
VOID SetHook_ZwReadVirtualMemory( void );
VOID SetHook_ZwQuerySystemInformation( void );
VOID SetHook_ZwQueryInformationProcess( void );
VOID SetHook_ZwGetContextThread( void );
VOID InterUnset( void );
VOID InterSet( void );